# Generated by Django 4.2.14 on 2024-07-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Librarian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("librarian_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("age", models.IntegerField()),
                ("address", models.TextField()),
                ("qualification", models.CharField(max_length=150)),
                ("library_name", models.CharField(max_length=150)),
                ("library_location", models.TextField()),
                ("library_image", models.ImageField(upload_to="library_images/")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("age", models.IntegerField()),
                ("address", models.TextField()),
                ("contact_no", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
