# Generated by Django 4.2.14 on 2024-07-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarian",
            name="library_image",
            field=models.ImageField(blank=True, null=True, upload_to="library_images/"),
        ),
    ]
