# Generated by Django 4.2.14 on 2024-07-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0002_alter_librarian_library_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Librarian",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("librarian", "Librarian"),
                    ("user", "User"),
                ],
                default="user",
                max_length=10,
            ),
        ),
    ]
