# Generated by Django 4.2.14 on 2024-07-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0003_delete_librarian_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("image", models.CharField(max_length=100)),
                ("is_open", models.BooleanField(default=True)),
            ],
        ),
    ]
