# Generated by Django 4.2.14 on 2024-07-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0004_library"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="image",
            field=models.ImageField(upload_to=None),
        ),
    ]
