# Generated by Django 4.2.14 on 2024-07-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0005_alter_library_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="is_open",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
