# Generated by Django 4.2.14 on 2024-07-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0006_alter_library_is_open"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="library",
            name="is_open",
        ),
        migrations.AlterField(
            model_name="library",
            name="image",
            field=models.ImageField(upload_to="upload_images/"),
        ),
    ]
