# Generated by Django 4.2.14 on 2024-07-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0007_remove_library_is_open_alter_library_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="is_open",
            field=models.BooleanField(default=False),
        ),
    ]
