# Generated by Django 4.2.14 on 2024-07-14 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0011_alter_library_librarian_delete_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="library",
            name="is_open",
        ),
    ]
