# Generated by Django 4.2.14 on 2024-07-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0014_alter_library_librarian"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="library",
            name="librarian",
        ),
        migrations.AddField(
            model_name="library",
            name="librarian_name",
            field=models.CharField(default="Temporary Librarian", max_length=100),
        ),
    ]
