# Generated by Django 4.2.14 on 2024-07-14 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0018_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="librarian",
            field=models.ForeignKey(
                limit_choices_to={"role": "librarian"},
                on_delete=django.db.models.deletion.CASCADE,
                to="libraryapp.user",
            ),
        ),
    ]
