# Generated by Django 4.2.14 on 2024-07-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0020_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="librarian",
            field=models.CharField(max_length=100),
        ),
    ]
