# Generated by Django 4.2.14 on 2024-07-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0023_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(unique=True),
        ),
    ]
