# Generated by Django 4.2.14 on 2024-07-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0029_booking_returned_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="library",
            old_name="name",
            new_name="library_name",
        ),
    ]
