# Generated by Django 4.2.14 on 2024-07-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0030_rename_name_library_library_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="librarian",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
