# Generated by Django 4.2.14 on 2024-07-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0032_alter_library_library_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="library",
            name="library_name",
            field=models.CharField(max_length=100),
        ),
    ]
