# Generated by Django 4.2.14 on 2024-07-17 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0035_alter_library_librarian"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="library",
            name="librarian",
        ),
        migrations.AddField(
            model_name="library",
            name="library",
            field=models.ForeignKey(
                limit_choices_to={"role": "librarian"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="libraryapp.user",
                unique=True,
            ),
        ),
    ]
