# Generated by Django 4.2.14 on 2024-07-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0036_remove_library_librarian_library_library"),
    ]

    operations = [
        migrations.RenameField(
            model_name="library",
            old_name="library",
            new_name="librarian",
        ),
    ]
