# Generated by Django 4.2.14 on 2024-07-17 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0037_rename_library_library_librarian"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="librarian",
            field=models.OneToOneField(
                limit_choices_to={"role": "librarian"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="libraryapp.user",
            ),
        ),
    ]
