# Generated by Django 4.2.14 on 2024-07-17 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0039_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="library_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="library",
            name="librarian",
            field=models.OneToOneField(
                limit_choices_to={"role": "librarian"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library",
                to="libraryapp.user",
            ),
        ),
    ]
