# Generated by Django 4.2.14 on 2024-07-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0040_user_library_name_alter_library_librarian"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="library_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
