# Generated by Django 4.2.14 on 2024-07-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0041_alter_user_library_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="library_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
        migrations.AddField(
            model_name="user",
            name="library_location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
