# Generated by Django 4.2.14 on 2024-07-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0042_user_library_image_user_library_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="book",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="user",
        ),
        migrations.RemoveField(
            model_name="library",
            name="librarian",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.DeleteModel(
            name="Language",
        ),
        migrations.DeleteModel(
            name="Library",
        ),
    ]
