# Generated by Django 4.2.14 on 2024-07-19 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0043_remove_booking_book_remove_booking_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="book_covers/"),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("fiction", "Fiction"),
                            ("novel", "Novel"),
                            ("fantasy", "Fantasy"),
                            ("Autobiography", "Autobiography"),
                            ("biography", "Biography"),
                            ("poetry", "Poetry"),
                            ("thriller", "Thriller"),
                        ],
                        default="fiction",
                        max_length=50,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("english", "English"), ("malayalam", "Malayalam")],
                        default="english",
                        max_length=50,
                    ),
                ),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "library_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="libraryapp.user",
                    ),
                ),
            ],
        ),
    ]
