# Generated by Django 4.2.14 on 2024-07-19 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0044_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="library_name",
            new_name="librarian",
        ),
    ]
