# Generated by Django 4.2.14 on 2024-07-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0046_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="accepted_conditions",
            field=models.BooleanField(default=False),
        ),
    ]
