# Generated by Django 4.2.14 on 2024-07-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0047_booking_accepted_conditions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="accepted_conditions",
        ),
        migrations.AlterField(
            model_name="booking",
            name="booked_on",
            field=models.DateTimeField(),
        ),
    ]
