# Generated by Django 4.2.14 on 2024-07-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0048_remove_booking_accepted_conditions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booked_on",
            field=models.DateField(),
        ),
    ]
