# Generated by Django 4.2.14 on 2024-07-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0050_librarybook"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LibraryBook",
        ),
    ]
